#!/bin/bash

################################################################################
# Discord Bot - Pre-Deployment Configuration
# Run this script to configure your deployment settings
# Usage: ./setup-config.sh
################################################################################

# Color codes
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

# Create or update deploy config
CONFIG_FILE=".deploy-config"

log_info "Discord Bot Deployment Configuration"
log_info "===================================="
echo ""

# Get configuration from user or use defaults
read -p "Enter your domain (default: discord-bot.example.com): " DOMAIN
DOMAIN="${DOMAIN:-discord-bot.example.com}"

read -p "Enter Discord Bot Token for MainBot: " MAINBOT_TOKEN
if [ -z "$MAINBOT_TOKEN" ]; then
    log_warning "No MainBot token provided - you'll need to add it later"
    MAINBOT_TOKEN="YOUR_TOKEN_HERE"
fi

read -p "Enter Discord Bot Token for PingBot: " PINGBOT_TOKEN
if [ -z "$PINGBOT_TOKEN" ]; then
    log_warning "No PingBot token provided - you'll need to add it later"
    PINGBOT_TOKEN="YOUR_TOKEN_HERE"
fi

read -p "Enter deployment environment (production/development, default: production): " ENVIRONMENT
ENVIRONMENT="${ENVIRONMENT:-production}"

read -p "Enter email for SSL certificates (default: admin@$DOMAIN): " SSL_EMAIL
SSL_EMAIL="${SSL_EMAIL:-admin@$DOMAIN}"

# Save configuration
cat > "$CONFIG_FILE" << EOF
# Discord Bot Deployment Configuration
# Auto-generated by setup-config.sh

DOMAIN="$DOMAIN"
ENVIRONMENT="$ENVIRONMENT"
SSL_EMAIL="$SSL_EMAIL"
MAINBOT_TOKEN="$MAINBOT_TOKEN"
PINGBOT_TOKEN="$PINGBOT_TOKEN"
ACTIVITY_SERVER_PORT="3002"
VITE_PORT="5174"

EOF

log_success "Configuration saved to $CONFIG_FILE"
echo ""
log_info "Configuration Summary:"
echo "  Domain: $DOMAIN"
echo "  Environment: $ENVIRONMENT"
echo "  SSL Email: $SSL_EMAIL"
echo ""

# Update .env files
log_info "Updating .env files..."

# Mainbot .env
cat > "Bothbots/Mainbot/.env" << EOF
NODE_ENV=$ENVIRONMENT
DISCORD_TOKEN=$MAINBOT_TOKEN
EOF
log_success "Updated Bothbots/Mainbot/.env"

# Pingbot .env
cat > "Bothbots/Pingbot/.env" << EOF
NODE_ENV=$ENVIRONMENT
DISCORD_TOKEN=$PINGBOT_TOKEN
EOF
log_success "Updated Bothbots/Pingbot/.env"

# Activity Server .env
cat > "activitys/.env" << EOF
NODE_ENV=$ENVIRONMENT
ACTIVITY_SERVER_PORT=3002
EOF
log_success "Updated activitys/.env"

echo ""
log_success "Configuration completed!"
echo ""
log_info "Next steps:"
echo "  1. Make the deploy script executable: chmod +x deploy.sh"
echo "  2. Run the deployment: sudo bash deploy.sh production"
echo ""
